Analyzing Quakes Events by Using K Means Clustering
===================================================

#### *Project 1 for Developing Data Product Course in Coursera Data Science Series*

##### Author: Lingyun Song

Requirement of this project
--------------------------
1. Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
2. Deploy the application on Rstudio's shiny server
3. Share the application link by pasting it into the text box below
4. Share your server.R and ui.R code on github

Introduction
------------

This shiny app is built for analyzing quakes events occurred in a cube near Fiji since 1964 by using k-means clustering method, with the purpose of finding the central areas of those earthquakes. It might be a useful tool for evaluating possibilities of areas hit by earthquakes in future.

### Dataset
Input dataset "quakes" are from R Datasets Package. They were generated by subsampling 1000  from 5000 seismic events of Richter magnitude larger than 4.0, collected by Dr. John Woodhouse at Harvard University. Quakes dataset are stored in a data frame with 1000 observations on 5 variables as following table. Users are able to choose 2 of the 5 variables for k-means analysis.

Column   |  Variable Names  |  Class     |    annotation 
-------  |  --------------- |  --------  |    -----------
[,1]     | lat              |  numeric   |  Latitude of event
[,2]     | long             |  numeric   |  Longitude of event
[,3]     | depth            |  numeric   |  Depth (km)
[,4]     | mag              |  numeric   |  Richter Magnitude
[,5]     | stations         |  numeric   |  Number of stations reporting 

### Algorithm

#### Clustering Algorithms
A Clustering Algorithm is a method to group a set of unlabelled data points into homogeneous classes or clusters, based on similarity.

#### K Means Clustering
K-means is one of the simplest unsupervised learning clustering algorithms that solve the well-known clustering problem, and is popular for cluster analysis in data mining. It belongs to Partitioning Algorithms, which construct a partition of a database D of n objects into a set of k clusters. Given a number "k", K-means clustering finds a partition of k clusters that optimizes the chosen partitioning criterion. Different to another very popular method PAM, each cluster in k-means is represented by the center of the cluster.

Instruction for users
---------------------
Please download the documentation file from https://github.com/lingyunsong/Developing-data-products/blob/master/Project1_v2/document.md  and read it.    

### Two options for using this shiny app:
1. Use server.R and ui.R on your own computer   
(1)Make sure that you have R installed.  
(2)Download the two files server.R and ui.R from https://github.com/lingyunsong/Developing-data-products/tree/master/Project1_v2   
(3)Place the files into an app directory (for example, the directory is named as "my_app") in your working directory. launch the app in R with the following commands:  

      install.packages("shiny")  
      library(shiny)  
      runApp("my_app")  

2. Use the shiny app as a web page(do not need install R)  
Click this link to see the web page: https://developingdataproductproject1.shinyapps.io/project/

### Operations on the app:

1. The plot at the left bottom shows within groups sum of squares by number of clusters extracted for determining the appropriate k value (number of clusters), with 2 selected variables from the selectInput boxes above.The cluster numbers showing on x-axis can be manipulated by a slidebar with numbers ranging from 2 to 20. 

2. The right bottom figure is a clusplot of k-means clustering analysis. You can choose either two from the five variables and a cluster number ranging from 1 to 10, which are listed in the selectInput boxes above,  to visualize the clustering result.
